import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    experimentChat: "Experiment Conversation (Read-only)",
    runStatus: "Run Status",
    errorDetail: "Error Detail",
    finalResult: "Final Result",
    workQuality: "Work Quality",
    quality: "Quality",
    efficiency: "Efficiency",
    negotiation: "Negotiation",
    generationFailed: "Generation failed",
    generationError: "Error connecting to the generation AI.",
    instantiationFailed: "Failed to instantiate team",
    agentChannelError: "Error registering agents/channel in workspace.",
    updatePromptError: "Failed to update task prompt before execution",
    runExperimentError: "Failed to run experiment with custom prompt:",
    stopExperimentError: "Failed to stop experiment:",
    saveExperimentError: "Failed to save experiment:",
    generalAgent: "General Agent",
    generalAssistant: "General Assistant",
    generalAssistantPrompt: "You are a general AI assistant. Answer concisely.",
    newAgent: "New Agent",
    collaborativeAgent: "Collaborative Agent",
    collaborativeAgentPrompt: "You are a collaborative agent in this channel. Answer concisely and help solve the task.",
    generatorTitle: "Generate Your Crew with AI",
    generatorSubtitle: "Enter a description and the AI will configure the corresponding Programmatic Agents and Channel.",
    placeholderGenerator: "Example: I need a team of copywriters. I want a persuasive copy agent, a proofreader, and a coordinator...",
    configObjective: "Objective / Task Prompt",
    configCriteria: "Evaluation Criteria",
    configAgents: "Specialist Agents",
    saveBtn: "Save",
    editBtn: "Edit",
    leaderBadge: "Leader",
  },
  es: {
    experimentChat: "Conversacion del Experimento (Lectura)",
    runStatus: "Estado de Corrida",
    errorDetail: "Detalle del Error",
    finalResult: "Resultado Final",
    workQuality: "Calidad del Trabajo",
    quality: "Calidad",
    efficiency: "Eficiencia",
    negotiation: "Negociacion",
    generationFailed: "Fallo en la generacion",
    generationError: "Error al conectar con la IA de generacion.",
    instantiationFailed: "Fallo al instanciar el equipo",
    agentChannelError: "Error al registrar agentes/canal en el workspace.",
    updatePromptError: "Error al actualizar el prompt de tarea antes de la ejecucion",
    runExperimentError: "Error al ejecutar el experimento con prompt personalizado:",
    stopExperimentError: "Error al detener el experimento:",
    saveExperimentError: "Error al guardar el experimento:",
    generalAgent: "Agente General",
    generalAssistant: "Asistente General",
    generalAssistantPrompt: "Eres un asistente general de IA. Responde de forma concisa.",
    newAgent: "Nuevo Agente",
    collaborativeAgent: "Agente Colaborador",
    collaborativeAgentPrompt: "Eres un agente colaborador en este canal. Responde de forma concisa y ayuda a resolver la tarea.",
    generatorTitle: "Generá tu Equipo con IA",
    generatorSubtitle: "Ingresá una descripción y la IA configurará los Agentes Programáticos y el Canal correspondiente.",
    placeholderGenerator: "Ejemplo: Necesito un equipo de redactores publicitarios. Quiero un agente especialista en copy persuasivo, un corrector ortográfico y un coordinador que apruebe y decida.",
    configObjective: "Objetivo / Prompt de Tarea",
    configCriteria: "Criterios de Evaluación",
    configAgents: "Agentes Especialistas",
    saveBtn: "Guardar",
    editBtn: "Editar",
    leaderBadge: "Líder",
  },
};
