import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    pageTitle: "Pipelines",
    pageSubtitle: "Deterministic, linear execution pipelines for sequential workflows",
    createTitle: "Create Pipeline",
    createSubtitle: "Define a rigid sequential pipeline of script and agent stages",
    pipelineNameLabel: "Pipeline ID / Name *",
    pipelineNamePlaceholder: "e.g. ci-deploy",
    descriptionLabel: "Description (optional)",
    descriptionPlaceholder: "Lint, test, build, and deploy the application",
    stagesLabel: "Stages",
    addStage: "Add Stage",
    stageName: "Stage Name",
    stageType: "Type",
    scriptName: "Script File or Inline Script",
    agentName: "Agent ID (optional)",
    prompt: "Prompt Instructions",
    cancel: "Cancel",
    creating: "Creating...",
    createPipeline: "Create Pipeline",
    createError: "Failed to create pipeline",
    emptyTitle: "No pipelines created",
    emptyDescription: "Create a pipeline to execute structured, multi-stage jobs",
    emptyButton: "Create Pipeline",
    delete: "Delete",
    viewDetails: "View Details",
    lastRun: "Last run",
    neverRun: "Never executed",
    stagesCount: "stages",
  },
  es: {
    pageTitle: "Pipelines",
    pageSubtitle: "Flujos de ejecución lineal, rígidos y deterministas para tareas secuenciales",
    createTitle: "Crear Pipeline",
    createSubtitle: "Define un pipeline secuencial rígido con etapas de script y agente",
    pipelineNameLabel: "ID / Nombre del Pipeline *",
    pipelineNamePlaceholder: "ej. ci-deploy",
    descriptionLabel: "Descripción (opcional)",
    descriptionPlaceholder: "Ejecutar lint, test, build y deploy de la aplicación",
    stagesLabel: "Etapas",
    addStage: "Agregar Etapa",
    stageName: "Nombre de la Etapa",
    stageType: "Tipo",
    scriptName: "Archivo de Script o Script Inline",
    agentName: "ID del Agente (opcional)",
    prompt: "Instrucciones del Prompt",
    cancel: "Cancelar",
    creating: "Creando...",
    createPipeline: "Crear Pipeline",
    createError: "Error al crear el pipeline",
    emptyTitle: "No hay pipelines creados",
    emptyDescription: "Crea un pipeline para ejecutar trabajos secuenciales estructurados",
    emptyButton: "Crear Pipeline",
    delete: "Eliminar",
    viewDetails: "Ver Detalles",
    lastRun: "Última ejecución",
    neverRun: "Nunca ejecutado",
    stagesCount: "etapas",
  },
};
