import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    runTitle: "Pipeline Execution Progress",
    statusRunning: "Running",
    statusCompleted: "Completed",
    statusFailed: "Failed",
    stageStatusPending: "Pending",
    stageStatusRunning: "Running Stage",
    stageStatusCompleted: "Completed",
    stageStatusFailed: "Failed",
    abort: "Abort Execution",
    duration: "Duration",
    startedAt: "Started at",
    finishedAt: "Finished at",
    viewLogs: "Stdout & Execution Logs",
    parsedOutput: "Structured Outputs",
    noOutput: "No structured output returned for this stage yet.",
    tokens: "Tokens",
    cost: "Cost",
  },
  es: {
    runTitle: "Progreso de Ejecución del Pipeline",
    statusRunning: "Ejecutando",
    statusCompleted: "Completado",
    statusFailed: "Fallido",
    stageStatusPending: "Pendiente",
    stageStatusRunning: "Ejecutando Etapa",
    stageStatusCompleted: "Completado",
    stageStatusFailed: "Fallido",
    abort: "Abortar Ejecución",
    duration: "Duración",
    startedAt: "Iniciado a las",
    finishedAt: "Finalizado a las",
    viewLogs: "Stdout y Logs de Ejecución",
    parsedOutput: "Outputs Estructurados",
    noOutput: "Aún no hay outputs estructurados registrados para esta etapa.",
    tokens: "Tokens",
    cost: "Costo",
  },
};
