import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    exportTitle: "Export Experiment Crew",
    exportSubtitle: "Convert agents and teams from this laboratory run into permanent workspace entities.",
    variantLabel: "Select Variant to Export",
    variantSingleTitle: "Single Programmatic Agent",
    variantSingleDesc: "Creates 1 permanent programmatic agent in your workspace.",
    variantHorizontalTitle: "Horizontal Multi-Agent Team",
    variantHorizontalDesc: "Creates 1 multi-agent team with broadcast interaction mode.",
    variantHierarchicalTitle: "Hierarchical Multi-Agent Team",
    variantHierarchicalDesc: "Creates 1 multi-agent team led by a coordinator agent.",
    channelNameLabel: "Workspace Team Name",
    channelNamePlaceholder: "Enter team name...",
    previewTitle: "Entities Preview",
    previewAgentNew: "New Agent (will be created)",
    previewAgentExisting: "Existing Agent (will be reused)",
    previewChannel: "Team (new UUID will be created)",
    btnExport: "Export to Workspace",
    btnExporting: "Exporting...",
    btnCancel: "Cancel",
    btnGoToAgent: "Go to Agent",
    btnGoToChannel: "Go to Team",
    btnClose: "Close",
    successTitle: "Export Successful!",
    successSubtitle: "The entities are now permanently registered in your workspace.",
    variantNotCompleted: "This variant has not completed running and cannot be exported.",
    statusExisting: "Existing",
    statusNew: "New",
  },
  es: {
    exportTitle: "Exportar Tripulación del Experimento",
    exportSubtitle: "Convertí los agentes y equipos de esta corrida de laboratorio en entidades permanentes del workspace.",
    variantLabel: "Seleccioná la Variante a Exportar",
    variantSingleTitle: "Agente Programático Individual",
    variantSingleDesc: "Crea 1 agente programático permanente en tu espacio de trabajo.",
    variantHorizontalTitle: "Equipo Multi-Agente Horizontal",
    variantHorizontalDesc: "Crea 1 equipo multi-agente con modo de interacción de difusión (broadcast).",
    variantHierarchicalTitle: "Equipo Multi-Agente Jerárquico",
    variantHierarchicalDesc: "Crea 1 equipo multi-agente liderado por un agente coordinador.",
    channelNameLabel: "Nombre del Equipo en Workspace",
    channelNamePlaceholder: "Ingresá el nombre del equipo...",
    previewTitle: "Vista Previa de Entidades",
    previewAgentNew: "Agente Nuevo (se va a registrar)",
    previewAgentExisting: "Agente Existente (se va a reutilizar)",
    previewChannel: "Equipo (se creará con un nuevo UUID)",
    btnExport: "Exportar a Workspace",
    btnExporting: "Exportando...",
    btnCancel: "Cancelar",
    btnGoToAgent: "Ir al Agente",
    btnGoToChannel: "Ir al Equipo",
    btnClose: "Cerrar",
    successTitle: "¡Exportación Exitosa!",
    successSubtitle: "Las entidades ya están registradas permanentemente en tu workspace.",
    variantNotCompleted: "Esta variante no completó su corrida y no se puede exportar.",
    statusExisting: "Existente",
    statusNew: "Nuevo",
  },
};
